2018-12-21 20:09:57,926 ERROR: Exception on /edit_profile [POST] [in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 509, in do_execute
    cursor.execute(statement, parameters)
sqlite3.IntegrityError: UNIQUE constraint failed: users.username

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/chen/Documents/workspace/github/microblog/app/routes.py", line 90, in edit_profile
    db.session.commit()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sqlalchemy/orm/scoping.py", line 153, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 954, in commit
    self.transaction.commit()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 467, in commit
    self._prepare_impl()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 447, in _prepare_impl
    self.session.flush()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2313, in flush
    self._flush(objects)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2440, in _flush
    transaction.rollback(_capture_exception=True)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 66, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 249, in reraise
    raise value
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2404, in _flush
    flush_context.execute()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sqlalchemy/orm/unitofwork.py", line 395, in execute
    rec.execute(self)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sqlalchemy/orm/unitofwork.py", line 560, in execute
    uow
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sqlalchemy/orm/persistence.py", line 177, in save_obj
    mapper, table, update)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sqlalchemy/orm/persistence.py", line 774, in _emit_update_statements
    execute(statement, multiparams)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 948, in execute
    return meth(self, multiparams, params)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 269, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1060, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1200, in _execute_context
    context)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1413, in _handle_dbapi_exception
    exc_info
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 265, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 248, in reraise
    raise value.with_traceback(tb)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 509, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) UNIQUE constraint failed: users.username [SQL: 'UPDATE users SET username=?, about_me=? WHERE users.id = ?'] [parameters: ('小尧大米粥', '我喜欢睡觉，我讨厌孤独', 1)] (Background on this error at: http://sqlalche.me/e/gkpj)
2018-12-21 20:59:00,696 INFO: Microblog startup [in /Users/chen/Documents/workspace/github/microblog/app/__init__.py:44]
2018-12-21 21:06:25,489 INFO: Microblog startup [in /Users/chen/Documents/workspace/github/microblog/app/__init__.py:44]
2018-12-21 21:07:41,834 INFO: Microblog startup [in /Users/chen/Documents/workspace/github/microblog/app/__init__.py:44]
2018-12-21 21:10:37,293 INFO: Microblog startup [in /Users/chen/Documents/workspace/github/microblog/app/__init__.py:44]
2018-12-21 21:10:42,836 INFO: Microblog startup [in /Users/chen/Documents/workspace/github/microblog/app/__init__.py:44]
2018-12-22 10:20:54,744 INFO: Microblog startup [in /Users/chen/Documents/workspace/github/microblog/app/__init__.py:44]
2018-12-22 10:24:46,508 INFO: Microblog startup [in /Users/chen/Documents/workspace/github/microblog/app/__init__.py:44]
2018-12-22 10:54:10,865 INFO: Microblog startup [in /Users/chen/Documents/workspace/github/microblog/app/__init__.py:44]
2018-12-26 09:27:13,756 INFO: Microblog startup [in /Users/chen/Documents/workspace/github/microblog/app/__init__.py:44]
2018-12-26 09:27:14,528 INFO: Microblog startup [in /Users/chen/Documents/workspace/github/microblog/app/__init__.py:44]
2018-12-26 10:03:59,881 INFO: Microblog startup [in /Users/chen/Documents/workspace/github/microblog/app/__init__.py:44]
2018-12-26 10:04:00,502 INFO: Microblog startup [in /Users/chen/Documents/workspace/github/microblog/app/__init__.py:44]
2018-12-26 10:05:01,674 INFO: Microblog startup [in /Users/chen/Documents/workspace/github/microblog/app/__init__.py:44]
2018-12-26 10:05:02,324 INFO: Microblog startup [in /Users/chen/Documents/workspace/github/microblog/app/__init__.py:44]
2018-12-26 10:05:35,530 INFO: Microblog startup [in /Users/chen/Documents/workspace/github/microblog/app/__init__.py:44]
2018-12-26 10:05:36,142 INFO: Microblog startup [in /Users/chen/Documents/workspace/github/microblog/app/__init__.py:44]
2018-12-26 11:05:23,798 INFO: Microblog startup [in /Users/chen/Documents/workspace/github/microblog/app/__init__.py:44]
2018-12-26 11:05:24,327 INFO: Microblog startup [in /Users/chen/Documents/workspace/github/microblog/app/__init__.py:44]
2018-12-26 11:30:30,177 INFO: Microblog startup [in /Users/chen/Documents/workspace/github/microblog/app/__init__.py:44]
2018-12-26 11:30:30,738 INFO: Microblog startup [in /Users/chen/Documents/workspace/github/microblog/app/__init__.py:44]
2018-12-26 11:32:19,638 INFO: Microblog startup [in /Users/chen/Documents/workspace/github/microblog/app/__init__.py:44]
2018-12-26 11:32:20,163 INFO: Microblog startup [in /Users/chen/Documents/workspace/github/microblog/app/__init__.py:44]
2018-12-26 14:56:54,269 INFO: Microblog startup [in /Users/chen/Documents/workspace/github/microblog/app/__init__.py:44]
2018-12-26 14:56:54,863 INFO: Microblog startup [in /Users/chen/Documents/workspace/github/microblog/app/__init__.py:44]
2018-12-26 15:06:20,733 INFO: Microblog startup [in /Users/chen/Documents/workspace/github/microblog/app/__init__.py:44]
2018-12-26 15:06:21,326 INFO: Microblog startup [in /Users/chen/Documents/workspace/github/microblog/app/__init__.py:44]
2018-12-26 15:16:45,117 INFO: Microblog startup [in /Users/chen/Documents/workspace/github/microblog/app/__init__.py:44]
2018-12-26 15:16:45,706 INFO: Microblog startup [in /Users/chen/Documents/workspace/github/microblog/app/__init__.py:44]
2018-12-26 15:24:14,175 INFO: Microblog startup [in /Users/chen/Documents/workspace/github/microblog/app/__init__.py:44]
2018-12-26 15:24:14,736 INFO: Microblog startup [in /Users/chen/Documents/workspace/github/microblog/app/__init__.py:44]
2018-12-26 15:29:39,129 INFO: Microblog startup [in /Users/chen/Documents/workspace/github/microblog/app/__init__.py:44]
2018-12-26 15:29:39,692 INFO: Microblog startup [in /Users/chen/Documents/workspace/github/microblog/app/__init__.py:44]
2018-12-26 15:31:10,102 INFO: Microblog startup [in /Users/chen/Documents/workspace/github/microblog/app/__init__.py:44]
