2018-12-26 21:28:13,439 ERROR: Exception on /login [GET] [in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/chen/Documents/workspace/github/microblog/app/routes.py", line 58, in login
    return render_template('login.html', form=form, title='Sign in')
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/templating.py", line 135, in render_template
    context, ctx.app)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/Users/chen/Documents/workspace/github/microblog/app/templates/login.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/chen/Documents/workspace/github/microblog/app/templates/base.html", line 32, in top-level template code
    {% block content %}{% endblock %}
  File "/Users/chen/Documents/workspace/github/microblog/app/templates/login.html", line 31, in block "content"
    <a href="{{ url_for('reset_password_reqeust') }}">click to Rest it</a>
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/helpers.py", line 356, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py", line 2061, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/helpers.py", line 345, in url_for
    force_external=external)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/werkzeug/routing.py", line 1776, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'reset_password_reqeust'. Did you mean 'reset_password_request' instead?
2018-12-26 21:28:26,214 ERROR: Exception on /login [GET] [in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/chen/Documents/workspace/github/microblog/app/routes.py", line 58, in login
    return render_template('login.html', form=form, title='Sign in')
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/templating.py", line 135, in render_template
    context, ctx.app)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/Users/chen/Documents/workspace/github/microblog/app/templates/login.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/chen/Documents/workspace/github/microblog/app/templates/base.html", line 32, in top-level template code
    {% block content %}{% endblock %}
  File "/Users/chen/Documents/workspace/github/microblog/app/templates/login.html", line 31, in block "content"
    <a href="{{ url_for('reset_password_reqeust') }}">click to Rest it</a>
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/helpers.py", line 356, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py", line 2061, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/helpers.py", line 345, in url_for
    force_external=external)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/werkzeug/routing.py", line 1776, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'reset_password_reqeust'. Did you mean 'reset_password_request' instead?
2018-12-26 21:28:57,589 INFO: Microblog startup [in /Users/chen/Documents/workspace/github/microblog/app/__init__.py:46]
2018-12-26 21:28:58,159 INFO: Microblog startup [in /Users/chen/Documents/workspace/github/microblog/app/__init__.py:46]
2018-12-26 21:30:52,014 INFO: Microblog startup [in /Users/chen/Documents/workspace/github/microblog/app/__init__.py:46]
2018-12-26 21:30:52,608 INFO: Microblog startup [in /Users/chen/Documents/workspace/github/microblog/app/__init__.py:46]
2018-12-26 21:39:40,805 INFO: Microblog startup [in /Users/chen/Documents/workspace/github/microblog/app/__init__.py:46]
2018-12-26 22:35:25,646 INFO: Microblog startup [in /Users/chen/Documents/workspace/github/microblog/app/__init__.py:48]
2018-12-26 22:38:30,895 INFO: Microblog startup [in /Users/chen/Documents/workspace/github/microblog/app/__init__.py:48]
2018-12-26 22:39:07,983 INFO: Microblog startup [in /Users/chen/Documents/workspace/github/microblog/app/__init__.py:48]
2018-12-26 22:39:51,307 INFO: Microblog startup [in /Users/chen/Documents/workspace/github/microblog/app/__init__.py:48]
2018-12-26 22:42:34,625 INFO: Microblog startup [in /Users/chen/Documents/workspace/github/microblog/app/__init__.py:48]
2018-12-26 22:42:35,250 INFO: Microblog startup [in /Users/chen/Documents/workspace/github/microblog/app/__init__.py:48]
2018-12-26 22:47:25,797 INFO: Microblog startup [in /Users/chen/Documents/workspace/github/microblog/app/__init__.py:48]
2018-12-26 22:47:26,499 INFO: Microblog startup [in /Users/chen/Documents/workspace/github/microblog/app/__init__.py:48]
2018-12-26 22:49:51,464 INFO: Microblog startup [in /Users/chen/Documents/workspace/github/microblog/app/__init__.py:48]
2018-12-26 22:49:52,194 INFO: Microblog startup [in /Users/chen/Documents/workspace/github/microblog/app/__init__.py:48]
2018-12-26 22:53:02,379 INFO: Microblog startup [in /Users/chen/Documents/workspace/github/microblog/app/__init__.py:48]
2018-12-26 22:53:02,990 INFO: Microblog startup [in /Users/chen/Documents/workspace/github/microblog/app/__init__.py:48]
2018-12-26 22:53:45,360 INFO: Microblog startup [in /Users/chen/Documents/workspace/github/microblog/app/__init__.py:48]
2018-12-26 22:53:45,982 INFO: Microblog startup [in /Users/chen/Documents/workspace/github/microblog/app/__init__.py:48]
2018-12-26 22:55:07,597 INFO: Microblog startup [in /Users/chen/Documents/workspace/github/microblog/app/__init__.py:48]
